# Generated by Django 3.2.4 on 2022-11-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='введите свое сообщение', verbose_name='текст')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
            ],
        ),
    ]
