# Generated by Django 3.2 on 2022-10-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_published',
            new_name='Опубликовано',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='Название',
            field=models.CharField(default='Описание прекрасно', help_text='Максимум 150 символов', max_length=150),
        ),
    ]
