# Generated by Django 3.2 on 2022-10-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221030_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Опубликовано', models.BooleanField(default=True)),
                ('Slug', models.CharField(max_length=200)),
                ('Название', models.CharField(default='Описание прекрасно', help_text='Максимум 150 символов', max_length=150)),
                ('Вес', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Опубликовано', models.BooleanField(default=True)),
                ('Slug', models.CharField(max_length=200)),
                ('Название тэга', models.CharField(default='Названия нет', help_text='Максимум 150 символов', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='Описание',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Название',
        ),
        migrations.AddField(
            model_name='item',
            name='Название товара',
            field=models.CharField(default='Названия нет', help_text='Максимум 150 символов', max_length=150),
        ),
    ]
