# Generated by Django 3.2 on 2022-10-30 14:24

import catalog.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221030_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Slug',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='Вес',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32766)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='Описание',
            field=models.TextField(validators=[catalog.validators.validate_perfect]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Slug',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
