# Generated by Django 3.2 on 2022-10-30 16:35

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20221030_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Вес',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Название',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Опубликовано',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Название товара',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Описание',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Опубликовано',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='Название тэга',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='Опубликовано',
        ),
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', help_text='Максимум 150 символов', max_length=150, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.IntegerField(default=100, help_text='Целое число x, 0 < x < 32767', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32766)], verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', help_text='Максимум 150 символов', max_length=150, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default='', help_text='Обязательно используйте слово роскошно или превосходно!', validators=[catalog.validators.validate_perfect], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', help_text='Максимум 150 символов', max_length=150, verbose_name='Название тэга'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='catalog.Tag', verbose_name='Тэги'),
        ),
    ]
