# Generated by Django 3.2 on 2022-11-02 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20221101_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'verbose_name': 'тэг', 'verbose_name_plural': 'тэги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.SmallIntegerField(default=100, help_text='Целое число x, 0 < x < 32767', validators=[django.core.validators.MinValueValidator(1)], verbose_name='вес'),
        ),
    ]
