# Generated by Django 3.2 on 2022-11-09 19:49

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20221109_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='media/%Y/%m', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='', help_text='Обязательно используйте слово роскошно или превосходно!', validators=[catalog.validators.validate_perfect], verbose_name='Описание'),
        ),
    ]
