# Generated by Django 3.2 on 2022-11-12 04:29

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='media/%Y/%m', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'изображение для галереи',
                'verbose_name_plural': 'изображения для галереи',
                'default_related_name': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='media/%Y/%m', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'главное изображение',
                'verbose_name_plural': 'главные изображения',
                'default_related_name': 'main_image',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='', help_text='Обязательно используйте слово роскошно или превосходно!', validators=[catalog.validators.validate_perfect], verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AddField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.item', verbose_name='товар'),
        ),
    ]
