# Generated by Django 3.2.4 on 2022-11-14 19:12

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='показывать на главной'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='', help_text='Обязательно используйте слово роскошно или превосходно!', validators=[catalog.validators.validate_perfect], verbose_name='Описание'),
        ),
    ]
